### ISSUE TITLE
[Score Server] - Development Environment Setup

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/conductor#23]
## Summary

Using this thread to track issues as I troubleshoot through the Score development environment setup

> [!NOTE]  
> All details and solutions will be outlined in the comments below

#### 1. Set up complementary services

```bash
git clone -b conductor https://github.com/overture-stack/composer.git
cd composer
```

#### 2. Run the conductor for Songs dev environment, this command will set up all complementary services for Song development.

```bash
make scoreDev
```

#### 3. Clone Score

```bash
git clone https://github.com/overture-stack/score.git
cd score
```

#### 4. Run the build

```bash
./mvnw clean install -DskipTests
```

#### 6. Change directory to the score-server and run the server

```bash
cd score-server/
mvn spring-boot:run -Dspring-boot.run.profiles=default,s3,secure,dev
```

**Comment by MitchellShiell** [comment]
# Unsatisfied dependency for downloadController

I'm encountering the following error when trying to start the application:

```bash
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'downloadController': Unsatisfied dependency expressed through field 'downloadService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 's3DownloadService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 's3.download.expiration' in value "${s3.download.expiration}"
```

It seems the application is unable to find the property `s3.download.expiration`. 
- `s3.download.expiration` looks to be  defined in the application.yaml

**Comment by leoraba** [comment]
Added the missing environment variable on application.yml on this [commit](https://github.com/overture-stack/score/commit/669bdf0b34fb2fcc57e01622a198d83f8045f91f)
